// app.js — MDP Generator logic

// toggle map for yes/no sub-fields
const TM = {
  pcoupl:  {sub:'pcoupl-sub',  yes:'pc-yes', no:'pc-no'},
  tcoupl:  {sub:'tcoupl-sub',  yes:'tc-yes', no:'tc-no'},
  rcoulomb:{sub:'rcoulomb-sub',yes:'rc-yes', no:'rc-no'},
  rvdw:    {sub:'rvdw-sub',    yes:'rv-yes', no:'rv-no'},
};

// which tab is active
let activeTab = 'md';

// UI helpers
function v(id){ return document.getElementById(id).value; }
function isOn(key){ return !document.getElementById(TM[key].sub).classList.contains('hidden'); }
function esc(s){ return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

function setSel(id, val){
  const el = document.getElementById(id); if(!el) return;
  for(let i = 0; i < el.options.length; i++)
    if(el.options[i].value === val){ el.selectedIndex = i; return; }
}

function toggleSection(key, show){
  const m = TM[key];
  document.getElementById(m.sub).classList.toggle('hidden', !show);
  document.getElementById(m.yes).classList.toggle('active',  show);
  document.getElementById(m.no ).classList.toggle('active', !show);
}

function applyFFDefaults(){
  const ff = v('ff');
  const d = FF[ff]; if(!d) return;
  const md = d.md;
  setSel('coulomb', md.coulomb);
  setSel('water',   d.water);
  setSel('tcoupl',  md.tcoupl);
  setSel('pcoupl',  md.pcoupl);
  setSel('constraints', md.constraints);
  document.getElementById('rcoul').value = md.rcoul;
  document.getElementById('rvdw').value  = md.rvdw;
  document.getElementById('ff-note').textContent = d.note ? '-> ' + d.note : '';
}

// line builder helpers
function buildLines(cb){
  const L = [];
  const c  = (t)      => L.push({t:'c', x:t});
  const s  = (t)      => L.push({t:'s', x:t});
  const b  = ()       => L.push({t:'b'});
  const kv = (k,val,cm) => L.push({t:'kv', k, val, cm});
  cb(c, s, b, kv);
  return L;
}

function renderLines(L){
  return L.map(l => {
    if(l.t === 'b')  return '';
    if(l.t === 'c')  return '<span class="line-comment">'+esc(l.x)+'</span>';
    if(l.t === 's')  return '<span class="line-section">'+esc(l.x)+'</span>';
    if(l.t === 'kv'){
      const k  = l.k.padEnd(26);
      const cm = l.cm ? '  <span class="line-comment">; '+esc(l.cm)+'</span>' : '';
      return '<span class="line-key">'+esc(k)+'</span>= <span class="line-val">'+esc(l.val)+'</span>'+cm;
    }
    return '';
  }).join('\n');
}

function plainText(L){
  return L.map(l => {
    if(l.t === 'b')  return '';
    if(l.t === 'c')  return l.x;
    if(l.t === 's')  return l.x;
    if(l.t === 'kv') return l.k.padEnd(26) + '= ' + l.val + (l.cm ? '  ; '+l.cm : '');
    return '';
  }).join('\n');
}

// shared context from UI
function getCtx(){
  const ff     = v('ff');
  const system = v('system');
  const water  = v('water');
  const em     = parseInt(v('em'));
  const equil  = parseFloat(v('equil'));
  const prod   = parseFloat(v('prod'));
  const dt     = parseFloat(v('dt'));
  const coulomb= v('coulomb');
  const cons   = v('constraints');
  const pbc    = v('pbc');
  const usePc  = isOn('pcoupl');
  const useTc  = isOn('tcoupl');
  const useRc  = isOn('rcoulomb');
  const useRv  = isOn('rvdw');
  const pcoupl = usePc ? v('pcoupl') : 'no';
  const tcoupl = useTc ? v('tcoupl') : 'no';
  const pres   = v('pres'), taup = v('taup'), compress = v('compress');
  const temp   = v('temp'), taut = v('taut');
  const rcoul  = useRc ? v('rcoul') : null;
  const rvdw   = useRv ? v('rvdw')  : null;
  const ffData = FF[ff] || {};
  const dispCorr = (ffData.md || {}).dispCorr || 'EnerPres';
  return {ff,system,water,em,equil,prod,dt,coulomb,cons,pbc,
          usePc,useTc,useRc,useRv,pcoupl,tcoupl,
          pres,taup,compress,temp,taut,rcoul,rvdw,dispCorr,ffData};
}

// generator: ions.mdp
function generateIons(ctx){
  const p = (ctx.ffData.ions) || {};
  const isStub = !ctx.ffData.ions || Object.keys(ctx.ffData.ions).includes('/* TODO */');
  const L = buildLines((c,s,b,kv) => {
    c('; ions.mdp -- generated by mdp-gen');
    c('; System: '+ctx.system+'  |  Force field: '+ctx.ff+'  |  Water: '+ctx.water);
    if(isStub){ c('; NOTE: placeholder values -- fill in parameters.js for this force field'); }
    b(); s('; Run control (energy minimisation for solvated+ion system)');
    kv('integrator', p.integrator||'steep');
    kv('nsteps',     p.nsteps||1000,       'short min before ion placement');
    kv('emtol',      p.emtol||1000.0,      'kJ/mol/nm');
    kv('emstep',     p.emstep||0.01);
    b(); s('; Output');
    kv('nstxout',    0); kv('nstvout',0); kv('nstfout',0); kv('nstlog',500); kv('nstenergy',500);
    b(); s('; Neighbor searching');
    kv('cutoff-scheme','Verlet'); kv('ns_type','grid'); kv('nstlist','10');
    b(); s('; Electrostatics');
    kv('coulombtype', p.coulombtype||ctx.coulomb);
    if(p.rcoulomb) kv('rcoulomb', p.rcoulomb);
    if((p.coulombtype||ctx.coulomb)==='PME'){ kv('pme_order','4'); kv('fourierspacing','0.16'); }
    b(); s('; van der Waals');
    kv('vdwtype','Cut-off');
    if(p.rvdw) kv('rvdw', p.rvdw);
    b(); s('; Periodic boundary conditions');
    kv('pbc', p.pbc||ctx.pbc);
    b(); s('; Temperature / pressure coupling — off for ions step');
    kv('tcoupl','no'); kv('pcoupl','no');
    b(); s('; Constraints — none for minimisation');
    kv('constraints','none');
  });
  return L;
}

// generator: em.mdp
function generateEM(ctx){
  const p = (ctx.ffData.em) || {};
  const isStub = !ctx.ffData.em;
  const L = buildLines((c,s,b,kv) => {
    c('; em.mdp -- generated by mdp-gen');
    c('; System: '+ctx.system+'  |  Force field: '+ctx.ff+'  |  Water: '+ctx.water);
    if(isStub){ c('; NOTE: placeholder values -- fill in parameters.js for this force field'); }
    b(); s('; Run control');
    kv('integrator', p.integrator||'steep');
    kv('nsteps',     p.nsteps||ctx.em,   'max '+ctx.em+' steps');
    kv('emtol',      p.emtol||1000.0,    'stop when max force < 1000 kJ/mol/nm');
    kv('emstep',     p.emstep||0.01,     'initial step size nm');
    b(); s('; Output');
    kv('nstxout',0); kv('nstvout',0); kv('nstfout',0); kv('nstlog','500'); kv('nstenergy','500');
    b(); s('; Neighbor searching');
    kv('cutoff-scheme','Verlet'); kv('ns_type','grid'); kv('nstlist','1');
    b(); s('; Electrostatics');
    kv('coulombtype', p.coulombtype||ctx.coulomb);
    if(p.rcoulomb) kv('rcoulomb', p.rcoulomb);
    if((p.coulombtype||ctx.coulomb)==='PME'){ kv('pme_order','4'); kv('fourierspacing','0.16'); }
    b(); s('; van der Waals');
    kv('vdwtype','Cut-off');
    if(p.rvdw) kv('rvdw', p.rvdw);
    kv('DispCorr', p.dispCorr||ctx.dispCorr);
    b(); s('; Periodic boundary conditions');
    kv('pbc', p.pbc||ctx.pbc);
    b(); s('; Constraints');
    kv('constraints', p.constraints||'none');
    b(); s('; No coupling during energy minimisation');
    kv('tcoupl','no'); kv('pcoupl','no');
  });
  return L;
}

// generator: nvt.mdp
function generateNVT(ctx){
  const p = (ctx.ffData.nvt) || {};
  const isStub = !ctx.ffData.nvt;
  const equilS = Math.round(ctx.equil * 1e6 / (ctx.dt * 1000));
  const L = buildLines((c,s,b,kv) => {
    c('; nvt.mdp -- generated by mdp-gen');
    c('; System: '+ctx.system+'  |  Force field: '+ctx.ff+'  |  Water: '+ctx.water);
    if(isStub){ c('; NOTE: placeholder values -- fill in parameters.js for this force field'); }
    b(); s('; Run control');
    kv('integrator', p.integrator||'md');
    kv('nsteps',     p.nsteps||equilS,  ctx.equil+' ns equilibration (NVT)');
    kv('dt',         p.dt||ctx.dt,      (p.dt||ctx.dt)*1000+' fs timestep');
    b(); s('; Output');
    kv('nstxout-compressed','5000'); kv('nstvout','0'); kv('nstfout','0'); kv('nstlog','5000'); kv('nstenergy','5000');
    b(); s('; Neighbor searching');
    kv('cutoff-scheme','Verlet'); kv('ns_type','grid'); kv('nstlist','10');
    if(p.rcoulomb) kv('rlist', p.rcoulomb);
    b(); s('; Electrostatics');
    kv('coulombtype', p.coulombtype||ctx.coulomb);
    if(p.rcoulomb) kv('rcoulomb', p.rcoulomb);
    if((p.coulombtype||ctx.coulomb)==='PME'){ kv('pme_order','4'); kv('fourierspacing','0.16'); }
    b(); s('; van der Waals');
    kv('vdwtype','Cut-off');
    if(p.rvdw) kv('rvdw', p.rvdw);
    kv('DispCorr', p.dispCorr||ctx.dispCorr);
    b(); s('; Temperature coupling — NVT');
    kv('tcoupl',   p.tcoupl||ctx.tcoupl);
    kv('tc-grps',  'System');
    kv('tau_t',    ctx.taut);
    kv('ref_t',    ctx.temp);
    b(); s('; No pressure coupling in NVT');
    kv('pcoupl','no');
    b(); s('; Periodic boundary conditions');
    kv('pbc', ctx.pbc);
    b(); s('; Constraints');
    kv('constraints',         p.constraints||ctx.cons);
    kv('constraint_algorithm','LINCS');
    kv('lincs_iter',          '1');
    kv('lincs_order',         '4');
    b(); s('; Generate velocities');
    kv('gen_vel',  'yes');
    kv('gen_temp', ctx.temp);
    kv('gen_seed', '-1');
  });
  return L;
}

// generator: npt.mdp
function generateNPT(ctx){
  const p = (ctx.ffData.npt) || {};
  const isStub = !ctx.ffData.npt;
  const equilS = Math.round(ctx.equil * 1e6 / (ctx.dt * 1000));
  const L = buildLines((c,s,b,kv) => {
    c('; npt.mdp -- generated by mdp-gen');
    c('; System: '+ctx.system+'  |  Force field: '+ctx.ff+'  |  Water: '+ctx.water);
    if(isStub){ c('; NOTE: placeholder values -- fill in parameters.js for this force field'); }
    b(); s('; Run control');
    kv('integrator', p.integrator||'md');
    kv('nsteps',     p.nsteps||equilS,  ctx.equil+' ns equilibration (NPT)');
    kv('dt',         p.dt||ctx.dt,      (p.dt||ctx.dt)*1000+' fs timestep');
    b(); s('; Output');
    kv('nstxout-compressed','5000'); kv('nstvout','0'); kv('nstfout','0'); kv('nstlog','5000'); kv('nstenergy','5000');
    b(); s('; Neighbor searching');
    kv('cutoff-scheme','Verlet'); kv('ns_type','grid'); kv('nstlist','10');
    if(p.rcoulomb) kv('rlist', p.rcoulomb);
    b(); s('; Electrostatics');
    kv('coulombtype', p.coulombtype||ctx.coulomb);
    if(p.rcoulomb) kv('rcoulomb', p.rcoulomb);
    if((p.coulombtype||ctx.coulomb)==='PME'){ kv('pme_order','4'); kv('fourierspacing','0.16'); }
    b(); s('; van der Waals');
    kv('vdwtype','Cut-off');
    if(p.rvdw) kv('rvdw', p.rvdw);
    kv('DispCorr', p.dispCorr||ctx.dispCorr);
    b(); s('; Temperature coupling');
    kv('tcoupl',  p.tcoupl||ctx.tcoupl);
    kv('tc-grps', 'System');
    kv('tau_t',   ctx.taut);
    kv('ref_t',   ctx.temp);
    b(); s('; Pressure coupling — NPT');
    kv('pcoupl',         p.pcoupl||ctx.pcoupl);
    kv('pcoupltype',     'isotropic');
    kv('tau_p',          ctx.taup);
    kv('ref_p',          ctx.pres);
    kv('compressibility',ctx.compress);
    b(); s('; Periodic boundary conditions');
    kv('pbc', ctx.pbc);
    b(); s('; Constraints');
    kv('constraints',         p.constraints||ctx.cons);
    kv('constraint_algorithm','LINCS');
    kv('lincs_iter',          '1');
    kv('lincs_order',         '4');
    b(); s('; Continue from NVT — no velocity generation');
    kv('gen_vel','no');
  });
  return L;
}

// generator: md.mdp  (production — unchanged from v0.2)
function generateMD(ctx){
  const prodS  = Math.round(ctx.prod  * 1e6 / (ctx.dt * 1000));
  const equilS = Math.round(ctx.equil * 1e6 / (ctx.dt * 1000));
  const L = buildLines((c,s,b,kv) => {
    c('; md.mdp -- production run -- generated by mdp-gen');
    c('; System: '+ctx.system+'  |  Force field: '+ctx.ff+'  |  Water: '+ctx.water);
    b(); s('; Run control');
    kv('integrator','md'); kv('nsteps',prodS,ctx.prod+' ns'); kv('dt',ctx.dt,ctx.dt*1000+' fs timestep');
    b(); s('; Output control');
    kv('nstxout-compressed','5000','trajectory every 10 ps');
    kv('nstvout','0'); kv('nstfout','0'); kv('nstlog','5000'); kv('nstenergy','5000');
    b(); s('; Neighbor searching');
    kv('cutoff-scheme','Verlet'); kv('ns_type','grid'); kv('nstlist','10');
    if(ctx.rcoul) kv('rlist', ctx.rcoul);
    b(); s('; Electrostatics');
    kv('coulombtype', ctx.coulomb);
    if(ctx.rcoul) kv('rcoulomb', ctx.rcoul);
    if(ctx.coulomb==='PME'){ kv('pme_order','4'); kv('fourierspacing','0.16'); }
    if(ctx.coulomb==='Reaction-Field') kv('epsilon-rf','0','tin-foil BC');
    b(); s('; van der Waals');
    kv('vdwtype','Cut-off');
    if(ctx.rvdw) kv('rvdw', ctx.rvdw);
    kv('DispCorr', ctx.dispCorr);
    b(); s('; Temperature coupling');
    kv('tcoupl', ctx.tcoupl);
    if(ctx.useTc){ kv('tc-grps','System'); kv('tau_t',ctx.taut); kv('ref_t',ctx.temp); }
    b(); s('; Pressure coupling');
    kv('pcoupl', ctx.pcoupl);
    if(ctx.usePc){ kv('pcoupltype','isotropic'); kv('tau_p',ctx.taup); kv('ref_p',ctx.pres); kv('compressibility',ctx.compress); }
    b(); s('; Periodic boundary conditions');
    kv('pbc', ctx.pbc);
    b(); s('; Constraints');
    kv('constraints',ctx.cons); kv('constraint_algorithm','LINCS'); kv('lincs_iter','1'); kv('lincs_order','4');
    b();
    c('; Equilibration run: use nsteps = '+equilS+' ('+ctx.equil+' ns)');
    c('; Energy minimization: use nsteps = '+ctx.em);
    c('; Water model: '+ctx.water);
  });
  return L;
}

// tab switching
function switchTab(tab){
  activeTab = tab;
  document.querySelectorAll('.tab-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.tab === tab);
  });
  document.querySelectorAll('.tab-pane').forEach(pane => {
    pane.classList.toggle('active', pane.id === 'pane-'+tab);
  });
}

// main generate — runs all 5 and populates all panes
function generate(){
  const ctx = getCtx();
  const generators = {
    ions: generateIons,
    em:   generateEM,
    nvt:  generateNVT,
    npt:  generateNPT,
    md:   generateMD,
  };
  for(const [name, fn] of Object.entries(generators)){
    const lines = fn(ctx);
    const pane  = document.getElementById('pane-'+name);
    if(pane) pane.querySelector('.output-code').innerHTML = renderLines(lines);
    // stash plain text for copy/download
    pane._lines = lines;
  }
  // make sure active tab is visible
  switchTab(activeTab);
}

// copy & download
function copyActive(){
  const pane = document.getElementById('pane-'+activeTab);
  const txt  = pane ? pane.querySelector('.output-code').innerText : '';
  navigator.clipboard.writeText(txt).then(() => {
    const btn = document.getElementById('copybtn');
    btn.textContent = 'copied!'; btn.classList.add('copied');
    setTimeout(() => { btn.textContent = 'copy'; btn.classList.remove('copied'); }, 2000);
  });
}

function downloadActive(){
  const pane = document.getElementById('pane-'+activeTab);
  if(!pane) return;
  const txt  = pane.querySelector('.output-code').innerText;
  const blob = new Blob([txt], {type:'text/plain'});
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = activeTab + '.mdp';
  a.click();
  URL.revokeObjectURL(url);
}

// init
applyFFDefaults();
switchTab('md');
